letters = ["a","b","c","d","e","f","g"]
letters.append("h")
print(letters)
letters.pop()
print(letters)
letters.pop(2)
print(letters)
letters.remove("e")
print(letters)
letters.reverse()
print(letters)
letter_tri= sorted(letters)  #letters.sort()
print(letter_tri)